apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-wallet
  namespace: ${KUBE_NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
