apiVersion: v1
kind: Service
metadata:
  name: auction-app-org1
  namespace: ${NS}
spec:
  type: NodePort
  selector:
    app: auction-app-org1
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30003
      protocol: TCP