apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-app-org1
  namespace: ${NS}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-app-org1
  template:
    metadata:
      labels:
        app: auction-app-org1
    spec:
      containers:
        - name: main
          image: node:23
          imagePullPolicy: IfNotPresent
          command: ["node", "/app/app.js"]
          envFrom:
            - configMapRef:
                name: app-fabric-org1-v1-map
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: fabricids
              mountPath: /fabric/application/wallet
            - name: fabric-ccp
              mountPath: /fabric/application/gateways
            - name: tlscerts
              mountPath: /fabric/tlscacerts
            - name: app-code
              mountPath: /app
              type: hostPath
              path: ./fabric-samples/auction-simple/application-javascript
      volumes:
        - name: fabric-ccp
          configMap:
            name: app-fabric-ccp-v1-map
        - name: fabricids
          configMap:
            name: app-fabric-ids-v1-map
        - name: tlscerts
          configMap:
            name: app-fabric-tls-v1-map
        - name: app-code
          hostPath:
            path: ./fabric-samples/auction-simple/application-javascript
            type: Directory