apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  
  nfs:
    path: /mnt/nfs_share/  
    server: 192.168.208.1  
  persistentVolumeReclaimPolicy: Retain  