apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: explorer-db-pvc
  namespace: ${KUBE_NAMESPACE}  
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client  
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: explorer-wallet-pvc
  namespace: ${KUBE_NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
